### ISSUE TITLE
PostgreSQL

### ISSUE THREAD

**Issue by marcelloinfoweb** [prontostack/pronto-fuel#13]
É possivel usar o postgresql no dev container?

Ou poderia ter a opção de escolher o DB.

**Comment by marcelloinfoweb** [comment]
Para usar com o postgresql, docker-composer.yml:

```yml
# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${APP_PORT:-3000}:3000'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
            - redis
    pgsql:
        image: 'postgres:15'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
            - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s
    pgadmin:
        image: 'dpage/pgadmin4'
        environment:
            PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
            PGADMIN_DEFAULT_PASSWORD: 'root'
            PGADMIN_LISTEN_PORT: 80
        ports:
            - '16543:80'
        volumes:
            - 'sail-pgadmin:/var/lib/pgadmin'
        depends_on:
            - pgsql
        networks:
            - sail
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    debugger:
        image: butschster/buggregator:latest
        networks:
            - sail
        ports: [ '23517:8000', '1025:1025', '9912:9912', '9913:9913' ]

networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
    sail-pgadmin:
        driver: local
    sail-redis:
        driver: local

```
